### ISSUE TITLE
There's no Import section

### ISSUE THREAD

**Issue by aes** [pulumi/pulumi-libvirt#451]
File: [themes/default/content/registry/packages/libvirt/api-docs/pool/_index.md](https://www.pulumi.com/registry/packages/libvirt/api-docs/pool/)

There's no explanation of how to import this resource

**Comment by iwahbe** [comment]
We generate this provider from github.com/dmacvicar/terraform-provider-libvirt, so our docs only contain what [upstream's docs](https://registry.terraform.io/providers/dmacvicar/libvirt/latest/docs/resources/pool) contain, and they don't have an import section either. If they add one, we will pick it up on their next release.
